#!/usr/bin/env bash
# Extract one release's notes from CHANGELOG.md, both layers.
#
# CHANGELOG.md is two layers on purpose, and its own header says so: the
# `## <version>` sections are generated by cog from conventional commits, and the
# `## Notes — <version>` sections below them are hand-written and carry the
# reasoning a commit subject cannot. A release body that shipped only the first
# would drop the only part a human wrote deliberately.
#
# This is a script rather than a heredoc inside release.yml because a release body
# is not something to debug by cutting tags. `scripts/release-notes.sh 0.4.0`
# prints exactly what the release will say, and the unit check at the bottom of
# this file runs in CI.
#
# Deliberately NOT `cog changelog` at publish time: cog regenerates from the git
# history it can see, so the body would be whatever the tooling derives on the
# runner rather than the file that was reviewed and committed. The changelog in
# the tag is the artifact; this reads it.
#
# Usage: scripts/release-notes.sh <tag> [changelog-path]
#        scripts/release-notes.sh --self-test

set -euo pipefail

changelog_for() {
	local tag="$1" file="$2"

	# The cog-generated block: from `## <tag> - <date>` to the next section
	# boundary, which is either the `- - -` separator cog writes between
	# releases or the next `## ` heading. Both, because the last section in the
	# file has no separator after it.
	awk -v tag="$tag" '
		$0 ~ "^## " tag " - " { inside = 1; next }
		inside && (/^- - -$/ || /^## /) { exit }
		inside { print }
	' "$file"

	# The hand-written notes, if this release has any. An em dash, as the file
	# uses. Absent is normal — notes are written when there is something to say.
	local notes
	notes="$(awk -v heading="## Notes — $tag" '
		$0 == heading { inside = 1; print; next }
		inside && (/^- - -$/ || /^## /) { exit }
		inside { print }
	' "$file")"

	if [ -n "$notes" ]; then
		printf '%s\n' "$notes"
	fi
}

self_test() {
	local tmp fail=0
	tmp="$(mktemp)"
	cat >"$tmp" <<'FIXTURE'
# Changelog

Preamble that must never appear in a release body.

- - -
## 9.9.9 - 2026-01-02
#### Features
- something new - (abc1234) - A Human

- - -

## 9.9.8 - 2026-01-01
#### Bug Fixes
- older release, must not leak - (def5678) - A Human

- - -

## Notes — 9.9.9

Hand-written reasoning for 9.9.9.

### A subsection

Still 9.9.9's notes.

## Notes — 9.9.8

Different release's notes.
FIXTURE

	local out
	out="$(changelog_for 9.9.9 "$tmp")"

	check() {
		if [ "$1" = "yes" ]; then
			grep -qF -- "$2" <<<"$out" || { echo "FAIL: missing '$2'" >&2; fail=1; }
		else
			grep -qF -- "$2" <<<"$out" && { echo "FAIL: leaked '$2'" >&2; fail=1; }
		fi
		return 0
	}

	check yes "something new"
	check yes "Hand-written reasoning for 9.9.9."
	# A `###` subsection belongs to the notes it sits under; stopping at any
	# heading rather than at `## ` exactly would truncate here.
	check yes "Still 9.9.9's notes."
	check no "older release, must not leak"
	check no "Different release's notes."
	check no "Preamble that must never appear"
	# The separator is a boundary, not content.
	check no "- - -"

	# A release with no hand-written notes must still produce the generated
	# block, and must not pick up the next release's notes.
	local bare
	bare="$(changelog_for 9.9.8 "$tmp")"
	grep -qF "older release" <<<"$bare" || { echo "FAIL: 9.9.8 lost its generated block" >&2; fail=1; }
	grep -qF "Hand-written reasoning" <<<"$bare" && { echo "FAIL: 9.9.8 picked up 9.9.9's notes" >&2; fail=1; }

	# An unknown tag is empty, not an error: the caller decides whether that is
	# fatal, and release.yml does treat it as fatal.
	[ -z "$(changelog_for 0.0.0 "$tmp")" ] || { echo "FAIL: unknown tag produced output" >&2; fail=1; }

	rm -f "$tmp"
	if [ "$fail" -eq 0 ]; then
		echo "release-notes.sh: self-test ok"
	fi
	return "$fail"
}

case "${1:-}" in
--self-test)
	self_test
	;;
"")
	echo "usage: $0 <tag> [changelog-path]" >&2
	exit 2
	;;
*)
	changelog_for "$1" "${2:-CHANGELOG.md}"
	;;
esac
